### ISSUE TITLE
Attribute composability improvements

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp#13]
# Description
Make attributes composable

# Breakdown
- Move common properties from AutomaticContainerRegistrationAttribute.cs and AutomaticConcretionContainerRegistrationAttribute.cs into a shared base class

# TODO
Consider how to make this more composable. Current suggestion is a step in the right direction but most likely not there yet

**Comment by JC008** [comment]
Also consider adding parameter / property support to allow further specialization.
